# SPDX-FileCopyrightText: 2023 Carmen Bianca BAKKER <carmenbianca@fsfe.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Update .pot file

on:
  push:
    branches:
      - main
    paths:
      - "src/reuse/**.py"

jobs:
  create-pot:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          # The main branch is protected. fsfe-system has been granted an
          # exception to the branch protection, so we'll use that account's
          # token to push to the main branch.
          token: ${{ secrets.FSFE_SYSTEM_TOKEN }}
      - name: Install gettext
        run: sudo apt-get install -y gettext
      - name: Create .pot file
        run: make create-pot
      # Normally, POT-Creation-Date changes in two locations. Check if the diff
      # includes more than just those two lines.
      - name: Check if sufficient lines were changed
        id: diff
        run:
          echo "changed=$(git diff -U0 | grep '^[+|-][^+|-]' | grep -Ev
          '^[+-]"POT-Creation-Date' | wc -l)" >> $GITHUB_OUTPUT
      - name: Commit and push updated reuse.pot
        if: ${{ steps.diff.outputs.changed != '0' }}
        run: |
          git config --global user.name "fsfe-system"
          git config --global user.email "<>"
          git add po/reuse.pot po/*.po
          git commit -m "Update reuse.pot"
          git push origin main
