# SPDX-FileCopyrightText: 2019 Free Software Foundation Europe e.V. <https://fsfe.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Python package

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Install reuse
        run: |
          python setup.py install
      - name: Run tests with pytest
        run: |
          make test

# Commented out because `cryptography` doesn't install on PyPy3
#
#  pypy3-test:
#    runs-on: ubuntu-latest
#    container: pypy:3
#    steps:
#      - uses: actions/checkout@v1
#      - name: Create alias to python
#        run: |
#          test -f /usr/local/bin/pypy && ln -s pypy /usr/local/bin/python
#          test -f /usr/local/bin/pypy3 && ln -s pypy3 /usr/local/bin/python
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r requirements-dev.txt
#      - name: Install reuse
#        run: |
#          python setup.py install
#      - name: Run tests with pytest
#        run: |
#          make test

  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Lint with PyLint
        run: |
          make lint

  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Test formatting with black
        run: |
          make blackcheck

  reuse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Install reuse
        run: |
          python setup.py install
      - name: Test REUSE compliance
        run: |
          make reuse

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Install reuse
        run: |
          python setup.py install
      - name: Create docs with Sphinx
        run: |
          make docs

  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build Dockerfile
        run: |
          docker build -t reuse .
      - name: Run Docker image
        run: |
          docker run -v "$(pwd):/data" reuse
